version: '2'

services:
    db:
        image: postgres:9.6
        volumes:
            - /var/fider/pg_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: fider
            POSTGRES_PASSWORD: s0m3g00dp4ssw0rd
    app:
        build:
            context: '.'
            dockerfile: Dockerfile
        image: getfider/fider:stable
        ports:
            - 9999:3000
        env_file: .env
        depends_on:
            - db
