version: '2'
services:
    db:
        restart: always
        image: postgres:9.6
        volumes:
            - /var/fider/pg_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: fider
            POSTGRES_PASSWORD: s0m3g00dp4ssw0rd

    app:
        restart: always
        image: getfider/fider:stable
        ports:
            - "9999:3000"
        environment:
            ###
            # REQUIRED
            #
            # All these settings are required
            ###

            # Use production for best performance
            # Use development for verbose logs
            GO_ENV: production

            # Connection string to the PostgreSQL database. 
            # This example uses the Docker service defined above
            DATABASE_URL: postgres://fider:s0m3g00dp4ssw0rd@db:5432/fider?sslmode=disable

            # CHANGE THIS! You can generate a strong secret at https://randomkeygen.com/
            JWT_SECRET: tXQhvSMWMS11qZ9euEhE6lf2ferf0FR6RYGd8iMXiTxxXtJ1XDVdTXPaLtV12ZGp

            # From which account e-mails will be sent (required)
            EMAIL_NOREPLY: noreply@yourdomain.com

            ###
            # EMAIL
            #
            # Either EMAIL_MAILGUN_* or EMAIL_SMTP_* is required
            ###

            # EMAIL_MAILGUN_API: key-yourkeygoeshere
            # EMAIL_MAILGUN_DOMAIN: yourdomain.com

            # EMAIL_SMTP_HOST: smtp.yourdomain.com
            # EMAIL_SMTP_PORT: 587
            # EMAIL_SMTP_USERNAME: user@yourdomain.com
            # EMAIL_SMTP_PASSWORD: s0m3p4ssw0rd

            ###
            # OPTIONAL
            #
            # Following settings are optional
            ###

            # Social OAuth: 
            # Read more on https://getfider.com/docs/configuring-oauth/

            # Facebook
            # OAUTH_FACEBOOK_APPID: <fb_app_id>
            # OAUTH_FACEBOOK_SECRET: <fb_app_secret>

            # Google
            # OAUTH_GOOGLE_CLIENTID: <google_app_id>
            # OAUTH_GOOGLE_SECRET: <google_app_secret>

            # GitHub
            # OAUTH_GITHUB_CLIENTID: <github_client_id>
            # OAUTH_GITHUB_SECRET: <github_secret>

        depends_on:
            - db
